stages:
- name: Build
  steps:
  - runScriptConfig:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1
      shellScript: |-
        dotnet tool install --global Cake.Tool --version 0.38.5
        export PATH="$PATH:/root/.dotnet/tools"

        dotnet cake build.cake --target=Test
        ls -al ./artifacts
- name: docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./artifacts/Hypomos.Silo/Dockerfile
      buildContext: ./artifacts/Hypomos.Silo/
      tag: hypomos-silo:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: harbor.cloud.bwalti.net/hypomos
  - publishImageConfig:
      dockerfilePath: ./artifacts/Hypomos.IdentityServer/Dockerfile
      buildContext: ./artifacts/Hypomos.IdentityServer/
      tag: hypomos-identity:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: harbor.cloud.bwalti.net/hypomos
  - publishImageConfig:
      dockerfilePath: ./artifacts/Hypomos.Api/Dockerfile
      buildContext: ./artifacts/Hypomos.Api
      tag: hypomos-api:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: harbor.cloud.bwalti.net/hypomos
  - publishImageConfig:
      dockerfilePath: ./artifacts/Hypomos.BlazorApp/Dockerfile
      buildContext: ./artifacts/Hypomos.BlazorApp
      tag: hypomos-blazorapp:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: harbor.cloud.bwalti.net/hypomos
  - publishImageConfig:
      dockerfilePath: ./src/WebApp/Dockerfile
      buildContext: ./src/WebApp/
      tag: hypomos-app:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: harbor.cloud.bwalti.net/hypomos
    env:
      PLUGIN_BUILD_ARGS: mode=testing
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./tst-config-permissions.yaml
  - applyYamlConfig:
      path: ./tst-issuer.yaml
  - applyYamlConfig:
      path: ./tst-certificate.yaml
  - applyYamlConfig:
      path: ./tst-orleans-kubernetes.yaml
  - applyYamlConfig:
      path: ./tst-deployment.yaml
  when:
    branch:
      include:
      - main
timeout: 60
notification: {}
