kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-reader
  namespace: hypomos-tst
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-read-config
  namespace: hypomos-tst
subjects:
- kind: ServiceAccount
  name: default # Name is case sensitive
  apiGroup: ""
roleRef:
  kind: Role
  name: config-reader
  apiGroup: ""