# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: hypomos-mvp
#extensions:
#- name: dapr
#registry: dapracr.azurecr.io
services:

- name: sqlserver
  image: mcr.microsoft.com/mssql/server:2019-latest
  env:
    - name: SA_PASSWORD
      value: "P@ssw0rd"
    - name: ACCEPT_EULA
      value: "Y"
  bindings:
    - port: 1433
      connectionString: Data Source=${host},${port};Initial Catalog=hypomosdb;User Id=sa;Password=${env:SA_PASSWORD};MultipleActiveResultSets=True;
- name: redis
  image: redis
  bindings:
    - port: 6379
- name: zipkin
  image: openzipkin/zipkin-slim
  bindings:
    - port: 9411
      containerPort: 9411
      protocol: http
- name: seq
  image: datalust/seq
  env:
    - name: "ACCEPT_EULA"
      value: "Y"
  bindings:
    - name: ui
      port: 5340
      protocol: http
      containerPort: 80
    - name: internal
      port: 5341
- name: silo-db
  image: minio/minio
  args: "minio server /data"
  env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: minio123
  bindings:
    - port: 9000
      protocol: tcp

- name: silo
  project: src/Hypomos.Silo/Hypomos.Silo.csproj
  bindings:
    - name: dashboard
      port: 9090
    - name: orleans-data
      port: 11111
      protocol: tcp
    - name: orleans-meta
      port: 33333
      protocol: tcp

- name: identity
  project: src/Hypomos.IdentityServer/Hypomos.IdentityServer.csproj
  bindings:
    - port: 5000
    
- name: api
  project: src/Hypomos.Api/Hypomos.Api.csproj
  bindings:
  - protocol: https
    port: 5010

- name: yarp
  project: src/YarpProxy/YarpProxy.csproj
  bindings:
  - name: https
    protocol: https
    port: 5101
  
- name: app
  dockerFile: src/WebApp/Dockerfile
  bindings:
  - protocol: http
    port: 3000